const STUDENT_DATA_REQUEST = "STUDENT_DATA_REQUEST"
const STUDENT_DATA_SUCCESS = "STUDENT_DATA_SUCCESS"
const STUDENT_DATA_FAILURE = "STUDENT_DATA_FAILURE"

export {
  STUDENT_DATA_REQUEST,
  STUDENT_DATA_SUCCESS,
  STUDENT_DATA_FAILURE, 
}